name: Deploy to AWS Elastic Beanstalk

on:
  pull_request:
    branches: [ master ]

jobs:
  build-images:
    name: Build base image of services
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build base image
        run: docker build -t sovent/dutycyclebase -f docker/production/base/Dockerfile .
        
      - name: Build api
        run: docker build -t sovent/dutycycleapi -f docker/production/api/Dockerfile .
        
      - name: Build worker
        run: docker build -t sovent/dutycycleworker -f docker/production/worker/Dockerfile .
        
      - name: Build migrations
        run: docker build -t sovent/dutycyclemigrations -f docker/production/migrations/Dockerfile .
        
      - name: Push api
        run: docker push sovent/dutycycleapi

      - name: Push api
        run: docker push sovent/dutycycleworker

      - name: Push api
        run: docker push sovent/dutycyclemigrations
