name: Deploy to AWS Elastic Beanstalk

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    types:
      - completed

jobs:
  build-images:
    name: Build base image of services
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build api
        run: docker build -t sovent/dutycycleapi -f docker/production/api/Dockerfile .
        
      - name: Build worker
        run: docker build -t sovent/dutycycleworker -f docker/production/worker/Dockerfile .
        
      - name: Build migrations
        run: docker build -t sovent/dutycyclemigrations -f docker/production/migrations/Dockerfile .
        
      - name: Push api
        run: docker push sovent/dutycycleapi

      - name: Push worker
        run: docker push sovent/dutycycleworker

      - name: Push migrations
        run: docker push sovent/dutycyclemigrations
        
  push-to-aws:
    name: "Push AWS to deploy"
    runs-on: ubuntu-latest
    needs:
      - build-images
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Zip task configuration
        run: zip -j deploy.zip docker/production/Dockerrun.aws.json

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
          
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: DutyCycle
          environment_name: Dutycycle-prod
          version_label: ${{ steps.buildnumber.outputs.build_number }}
          region: eu-central-1
          deployment_package: deploy.zip
