name: Run integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker
        run: docker login -u ${{ DOCKER_USER }} -p ${{ DOCKER_PASSWORD }}
      
      - name: Build image
        run: docker-compose -f DutyCycle.IntegrationTests/docker-compose.yml build
        
      - name: Run integration tests
        run: docker-compose -f DutyCycle.IntegrationTests/docker-compose.yml run --rm tests
