name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
        
      - name: Run tests
        run: make run-unit-tests
        
  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Run integration tests
        run: make run-integration-tests
