name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
        
      - name: Run tests
        run: dotnet test DutyCycle.Tests
        
  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build image
        run: docker-compose -f DutyCycle.IntegrationTests/docker-compose.yml build
        
      - name: Run integration tests
        run: docker-compose -f DutyCycle.IntegrationTests/docker-compose.yml run --rm tests
